name: Hello world

# trigger manually
on: workflow_dispatch

jobs:
   build:
       runs-on: ubuntu-latest
       steps:
           - name: Build Step
             run: echo "A demo build"
   test:
       runs-on: ubuntu-latest
       needs: build
       steps:
          - name: Test phase
            run: echo "Running Test cases"

   deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
          - name: Deploy the app
            run: echo "Deploying the app"

